"""CyberSym product identity — user-facing name and signature."""

COMPANY = "CyberSym"
PRODUCT = "CyberSym SecureTrade 2"
PRODUCT_SHORT = "SecureTrade"
PRODUCT_LINE = "SecureTrade"
VERSION = "2.1.0"
SIGNATURE = "A CyberSym product"
COPYRIGHT = "© CyberSym. All rights reserved."
USER_AGENT = "CyberSym-SecureTrade/2.1"
TAGLINE = "Intelligent enough to find the opportunity. Secure enough to know when to walk away."
GUARDIAN_NAME = "CyberSym Guardian"
ACADEMY_NAME = "CyberSym Academy"
EDITION_PERSONAL = "personal"
EDITION_PROFESSIONAL = "professional"
EDITION_ENTERPRISE = "enterprise"
